//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerCode { get; set; }
        public string CompanyName { get; set; }
        public int CustomerType { get; set; }
        public int Industry { get; set; }
        public bool Active { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string CreditTerm { get; set; }
        public string TaxCode { get; set; }
        public string Currency { get; set; }
        public decimal Creditlimit { get; set; }
        public decimal Balance { get; set; }
        public int Status { get; set; }
        public int DeliveryAddress { get; set; }
    }
}
