//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public byte[] barcode { get; set; }
        public string VendorId { get; set; }
        public string VendorItemNo { get; set; }
        public string Brand { get; set; }
        public string Currency { get; set; }
        public string CatCode { get; set; }
        public string Warehouse { get; set; }
        public decimal MaxQty { get; set; }
        public decimal MinQty { get; set; }
        public decimal ReorderQty { get; set; }
        public string StockUnit { get; set; }
        public string AccGroup { get; set; }
        public decimal UnitSellPrice { get; set; }
        public decimal AvgUnitCost { get; set; }
        public bool IsStockItem { get; set; }
        public bool InActive { get; set; }
        public Nullable<decimal> UnitWeight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> WeightFactor { get; set; }
        public string Dimension { get; set; }
        public string ImageLocate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
