//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KIMEntities : DbContext
    {
        public KIMEntities()
            : base("name=KIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<SKItemMaster> SKItemMasters { get; set; }
        public virtual DbSet<SKU> SKUs { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<Exchange> Exchanges { get; set; }
        public virtual DbSet<CreditTerm> CreditTerms { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryAddr> DeliveryAddrs { get; set; }
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WareHouse> WareHouses { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<ItemMasterPic> ItemMasterPics { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<SKDOCH> SKDOCHes { get; set; }
        public virtual DbSet<SKReceiveItem> SKReceiveItems { get; set; }
    }
}
