//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LangDict
    {
        public int Id { get; set; }
        public string Keyword { get; set; }
        public string EN_text { get; set; }
        public string KH_text { get; set; }
        public string TH_text { get; set; }
    }
}
