//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHH
    {
        public string OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string DeliveryAddr { get; set; }
        public int OrderStatus { get; set; }
        public string Currency { get; set; }
        public decimal OrderAmount { get; set; }
        public string CreditTerm { get; set; }
        public System.DateTime Duedate { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
