//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileItem
    {
        public int itemId { get; set; }
        public int ProfileId { get; set; }
        public string ItemNo { get; set; }
        public string RawMat { get; set; }
        public string Unit { get; set; }
        public decimal Qty { get; set; }
        public string Remark { get; set; }
    }
}
