//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIssueItem
    {
        public int Id { get; set; }
        public bool IsPosted { get; set; }
        public string SK_Code { get; set; }
        public string SKI_ISSUE_NUM { get; set; }
        public int ItemId { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Currency { get; set; }
        public string Unit { get; set; }
        public decimal IssueQty { get; set; }
        public decimal UnitCost { get; set; }
        public decimal TotalItemCost { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalItemPrice { get; set; }
    }
}
