//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKItemMaster
    {
        public int ID { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string SKU { get; set; }
        public string PurUnit { get; set; }
        public string ItemImg { get; set; }
        public int Category { get; set; }
        public string VendorCode { get; set; }
        public decimal SKUWeightG { get; set; }
    }
}
