//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKReceiveH
    {
        public int DOC_ID { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string PostedBy { get; set; }
        public string SK_Code { get; set; }
        public string DOC_NUM { get; set; }
        public System.DateTime DocDate { get; set; }
        public string Reason { get; set; }
        public string ReceiveBy { get; set; }
        public string Remark { get; set; }
        public string Currency { get; set; }
        public decimal TaxAndClearing { get; set; }
        public decimal TransportCost { get; set; }
        public decimal OtherServices { get; set; }
        public decimal TotalItemCost { get; set; }
        public decimal TotalAmount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
