//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKReceiveItem
    {
        public int SKI_ID { get; set; }
        public bool IsPosted { get; set; }
        public string SK_Code { get; set; }
        public string SKR_DOC_NUM { get; set; }
        public int ItemId { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Currency { get; set; }
        public string Unit { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Qty { get; set; }
        public decimal TotalItemCost { get; set; }
        public decimal TaxClearing { get; set; }
        public decimal Transport { get; set; }
        public decimal OtherCost { get; set; }
        public decimal ItemTotalAmount { get; set; }
        public decimal AvgUnitCost { get; set; }
    }
}
