//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIM.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int LogId { get; set; }
        public string LoginName { get; set; }
        public System.DateTime LoginDT { get; set; }
        public Nullable<System.DateTime> LogoutDT { get; set; }
        public string ComputerName { get; set; }
    }
}
